# Generated by Django 6.1 on 2026-08-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_comment_user_alter_comment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_total_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_avr_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
